from flask import Flask, request, jsonify
from flask_mysqldb import MySQL
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# MySQL Configuration
app.config['MYSQL_HOST'] = 'localhost'
app.config['MYSQL_USER'] = 'root'
app.config['MYSQL_PASSWORD'] = 'admin'
app.config['MYSQL_DB'] = 'resume_ai'

mysql = MySQL(app)


def _json_body():
    data = request.get_json(silent=True)
    return data if isinstance(data, dict) else {}


@app.route('/', methods=['GET'])
def home():
    return jsonify({
        "message": "AI Resume Builder backend is running",
        "available_endpoints": ["POST /register", "POST /login", "POST /generate_resume", "GET /health"]
    })


@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "ok"})

# ---------------- REGISTER ----------------
@app.route('/register', methods=['POST'])
def register():
    data = _json_body()
    name = (data.get('name') or '').strip()
    email = (data.get('email') or '').strip()
    password = data.get('password') or ''

    if not name or not email or not password:
        return jsonify({"message": "name, email and password are required"}), 400

    cur = mysql.connection.cursor()
    try:
        cur.execute(
            "INSERT INTO users(name,email,password) VALUES(%s,%s,%s)",
            (name, email, password)
        )
        mysql.connection.commit()
    except Exception as exc:
        mysql.connection.rollback()
        message = str(exc).lower()
        if "duplicate" in message or "unique" in message:
            return jsonify({"message": "Email already registered"}), 409
        return jsonify({"message": "Failed to register user"}), 500
    finally:
        cur.close()

    return jsonify({"message": "User Registered Successfully"})


# ---------------- LOGIN ----------------
@app.route('/login', methods=['POST'])
def login():
    data = _json_body()
    email = (data.get('email') or '').strip()
    password = data.get('password') or ''

    if not email or not password:
        return jsonify({"message": "email and password are required"}), 400

    cur = mysql.connection.cursor()
    try:
        cur.execute(
            "SELECT id FROM users WHERE email=%s AND password=%s",
            (email, password)
        )
        user = cur.fetchone()
    except Exception:
        return jsonify({"message": "Login failed due to server error"}), 500
    finally:
        cur.close()

    if user:
        return jsonify({"user_id": user[0]})
    else:
        return jsonify({"message": "Invalid credentials"}), 401


# ---------------- GENERATE RESUME ----------------
@app.route('/generate_resume', methods=['POST'])
def generate_resume():
    data = _json_body()

    user_id = data.get('user_id')
    template = (data.get('template') or '').strip()
    description = (data.get('description') or '').strip()

    if not user_id or not template or not description:
        return jsonify({"message": "user_id, template and description are required"}), 400

    # Simple formatted resume (AI can be added later)
    resume_content = f"""
Resume Template: {template}

Profile Summary:
{description}

--------------------------
Generated by AI Resume Builder
"""

    cur = mysql.connection.cursor()
    try:
        cur.execute(
            "INSERT INTO resumes(user_id, template_type, content) VALUES(%s,%s,%s)",
            (user_id, template, resume_content)
        )
        mysql.connection.commit()
    except Exception:
        mysql.connection.rollback()
        return jsonify({"message": "Failed to save generated resume"}), 500
    finally:
        cur.close()

    return jsonify({"resume": resume_content})


if __name__ == '__main__':
    app.run(debug=True)